name = "steeler-logbook-sync"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "SYNC_DB"
database_name = "steeler_logbook_sync_staging"
database_id = "e71fb407-9072-45f8-bdc0-500936e54470"

[vars]
SYNC_OWNER_ID = "steeler"
